base:
  project_name: MLOps_Workshop
  random_state: 20
  target_col: charges

data_source:
  raw_data: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance_processed.csv

split_data:
  train_path: data/processed/insurance_processed_train.csv
  test_path: data/processed/insurance_processed_test.csv
  test_size: 0.2

estimators:
  ElasticNet: 
    params: 
      alpha: 0.9
      l1_ratio: 0.6

model_path : model/models.joblib

reports:
  params: reports/params.json
  score: report/scores.json
  
