base:
  project_name: MLOps_Workshop
  random_state: 20
  target_col: charges

data_source:
  raw_data: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance_processed.csv

split_data:
  train_path: data/processed/insurance_processed_train.csv
  test_path: data/processed/insurance_processed_test.csv
  test_size: 0.2

estimators:
  ElasticNet: 
    params: 
      alpha: 0.9
      l1_ratio: 0.3

model_path : models/models.joblib

# reports:
#   params: reports/params.json
#   score: reports/scores.json
  
mlflow_config:
  artifacts_dir: artifacts
  experiment_name: insurance_exp
  run_name: mlops
  registered_model_name: ElasticNet
  remote_server_uri: http://127.0.0.1:5000  # MLFlow only works with port 5000
