# Generated by Django 5.1.6 on 2025-02-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mlops',
            new_name='aissms',
        ),
    ]
